### ISSUE TITLE
CONFIG!!!

### ISSUE THREAD

**Issue by remotevase** [remotevase/UltimateRanks#1]
The config doesn't save on enable. I have /resources/<filename>.yml
When I run the plugin and open it up, it doesnt save. Help please @ImagicalGamer @Taki21 I know you guys rock at configs

**Comment by remotevase** [comment]
bump @ImagicalGamer @Taki21 @TheDragonRing

**Comment by remotevase** [comment]
HELP ME!!!! WHY DOES NO ONE CARE ABOUT THIS PLUGIN! :sob: :disappointed: :crying_cat_face: 
@Taki21 SAVE MY LIFE ALREADY!

**Comment by Taki21** [comment]
SORRY!

**Comment by Taki21** [comment]
IM CHECKING  XD

**Comment by Taki21** [comment]
LOL Like I Told @TheDragonRing IF U have a resource folder I WILL GO CRAZY
https://45.media.tumblr.com/00ab7c6e612d076444821bc41abb06fa/tumblr_ndm99ew37W1u06e3ko1_400.gif
If u have a resource folder dont use "/config.yml" etc use "config.yml"

**Comment by remotevase** [comment]
Hey! I didn't say 

>  @Taki21 SAVE MY LIFE ALREADY!

Why'd you edit that?

**Comment by applqpak** [comment]
LOL xD

**Comment by remotevase** [comment]
Reopened it still doesn't work. Do I need an array? I still dont understand arrays, though...
@Taki21 '

**Comment by Taki21** [comment]
Thx Im Posting a new Array Lesson on IM xD

**Comment by Taki21** [comment]
What Da! The "/" was for the configs outside of da resources folder...?

**Comment by Taki21** [comment]
PLEASE TELL ME DAT WORKS :(

**Comment by remotevase** [comment]
DAT WORKS!!!!!!!!!! HOW'D YOU DO IT?

**Comment by Taki21** [comment]
lolol saveResource :)

**Comment by remotevase** [comment]
Publishing to IM forums now
