### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by remotevase** [remotevase/UltimateRanks#2]
Notice: Undefined variable: rank in ___________\ImagicalMine- Everything 0.14\ImagicalMine0.14\plugins\UltimateRanks\src\UltimateRanks\UltimateRanks.php on line 75

Notice: Undefined variable: rank in ________\ImagicalMine- Everything 0.14\ImagicalMine0.14\plugins\UltimateRanks\src\UltimateRanks\UltimateRanks.php on line 117

Notice: Undefined variable: rank in ___________-\ImagicalMine- Everything 0.14\ImagicalMine0.14\plugins\UltimateRanks\src\UltimateRanks\UltimateRanks.php on line 159

Notice: Undefined variable: rank in ______\ImagicalMine- Everything 0.14\ImagicalMine0.14\plugins\UltimateRanks\src\UltimateRanks\UltimateRanks.php on line 201

Notice: Undefined variable: rank in ____________\ImagicalMine- Everything 0.14\ImagicalMine0.14\plugins\UltimateRanks\src\UltimateRanks\UltimateRanks.php on line 243

@Taki21 what? @applqpak what? You guys usually know about errors like these...
$rank isnt even **there** on line 75!

**Comment by Taki21** [comment]
ill check

**Comment by Taki21** [comment]
Ur last commit should work

**Comment by remotevase** [comment]
I tried, and got this

**Comment by remotevase** [comment]
Going to test again in a few hours. See you then, github!

**Comment by remotevase** [comment]
@Taki21 @applqpak for now, put this issue on hold. I'll resume later

**Comment by remotevase** [comment]
Oh I think I fixed it
