### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BogdanMakarchuk** [remotevase/UltimateRanks#3]
[Server] [20:28:22] [Server thread/INFO]: 读取中... Ultimateranks v1.0.0
[Server] [20:28:22] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected '@'" (EXCEPTION) in "/UltimateRanks-master/src/UltimateRanks/UltimateRanks" at line 31
[Server] [20:28:22] [Server thread/EMERGENCY]: Произошла фатальная ошибка и сервер вышел из строя. Создание аварийного дампа
[Server] [20:28:22] [Server thread/EMERGENCY]: Пожалуйста, загрузите файл"/storage/emulated/0/PocketMine/crashdumps/CrashDump_Tue_Jun_21-20.28.22-UTC_2016.log" в краш-архив и отправьте ссылку на страницу исправления ошибок. Дайте как можно больше информации.
[PocketMine] Server was stopped.

**Comment by remotevase** [comment]
Ha lol oops XD
Thanks @Taki21

**Comment by Taki21** [comment]
np :)
